export const EXPENSE_LABEL_OPTIONS = [
  'SALAIRE',
  'CARBURANT',
  'LOYER',
  'FOURNITURE DE BUREAU',
  'ENTRETIEN ET REPARATION',
  'PUBLICITE ET PROMOTION',
  'ASSURANCE',
  "FRAIS D'ADMINISTRATION",
  'FRAIS DE COMMUNICATION',
  "FRAIS D'INTERNET",
  'FRAIS DE BANQUE',
  'TRANSPORT',
  'EAU PORTABLE',
  'EAU DINEPA',
  'AMORTISSEMENT',
  'FRAIS DE CONSULTATION',
  'AUTRES DEPENSES',
] as const;

export const EXPENSE_LABEL_OTHER = 'AUTRES DEPENSES';
