import { StyleSheet } from 'react-native';

import { BrandColors } from '@/constants/brand';
import { Spacing } from '@/constants/theme';

export const accountingStyles = StyleSheet.create({
  blocked: { flex: 1, justifyContent: 'center', padding: Spacing.five },
  blockedText: { textAlign: 'center', color: BrandColors.textMuted },
  error: { color: BrandColors.danger, fontWeight: '600', fontSize: 13 },
  ok: { color: BrandColors.ok, fontWeight: '600', fontSize: 13 },
  empty: { color: BrandColors.textMuted, textAlign: 'center', paddingVertical: Spacing.two },
  kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two },
  section: { fontSize: 16, fontWeight: '800', color: BrandColors.text, marginTop: Spacing.two },
  meta: { color: BrandColors.textMuted, fontSize: 12 },
  card: {
    backgroundColor: BrandColors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BrandColors.border,
    padding: Spacing.three,
    gap: 6,
  },
  cardTitle: { fontWeight: '800', color: BrandColors.text, fontSize: 15 },
  row: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, alignItems: 'center' },
  rowLabel: { color: BrandColors.text, flex: 1, fontSize: 13 },
  rowValue: { color: BrandColors.text, fontWeight: '700', fontSize: 13 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: BrandColors.borderStrong,
    backgroundColor: BrandColors.surface,
    flexGrow: 0,
    flexShrink: 0,
    alignSelf: 'center',
  },
  chipActive: { backgroundColor: BrandColors.primary, borderColor: BrandColors.primary },
  chipText: { color: BrandColors.text, fontWeight: '600', fontSize: 12 },
  chipTextActive: { color: '#fff' },
  input: {
    borderWidth: 1,
    borderColor: BrandColors.borderStrong,
    borderRadius: 12,
    paddingHorizontal: Spacing.three,
    paddingVertical: 12,
    fontSize: 16,
    color: BrandColors.text,
    backgroundColor: BrandColors.surface,
  },
  primaryBtn: {
    backgroundColor: BrandColors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondaryBtn: {
    backgroundColor: BrandColors.surface,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BrandColors.borderStrong,
  },
  dangerBtn: {
    backgroundColor: BrandColors.danger,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryBtnText: { color: '#fff', fontWeight: '700' },
  secondaryBtnText: { color: BrandColors.text, fontWeight: '700' },
  disabled: { opacity: 0.55 },
  line: { color: BrandColors.textMuted, fontSize: 12 },
  stickyHeader: {
    backgroundColor: BrandColors.bg,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.two,
    gap: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: BrandColors.border,
  },
  fyChipScroll: {},
  fyMeta: { color: BrandColors.textMuted, fontSize: 11 },
  subTabScroll: { paddingHorizontal: Spacing.three, paddingBottom: 6 },
  tableHead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: BrandColors.border,
    gap: 6,
  },
  tableHeadText: { color: BrandColors.textMuted, fontSize: 11, fontWeight: '700' },
  denseRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 7,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: BrandColors.border,
    gap: 6,
  },
  denseRowAlt: { backgroundColor: BrandColors.surfaceSoft },
  colCode: { width: 52, color: BrandColors.text, fontSize: 12, fontWeight: '700' },
  colName: { flex: 1, color: BrandColors.text, fontSize: 12 },
  colMuted: { flex: 1, color: BrandColors.textMuted, fontSize: 12 },
  colAmt: { width: 72, color: BrandColors.text, fontSize: 12, textAlign: 'right', fontVariant: ['tabular-nums'] },
  colDate: { width: 78, color: BrandColors.textMuted, fontSize: 11 },
  entryHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 10,
    paddingBottom: 4,
    paddingHorizontal: 4,
  },
  entryHeadTitle: { fontWeight: '800', color: BrandColors.text, fontSize: 13, flex: 1 },
  fieldLabel: { color: BrandColors.textMuted, fontSize: 12, fontWeight: '600' },
  pickerBtn: {
    borderWidth: 1,
    borderColor: BrandColors.borderStrong,
    borderRadius: 12,
    paddingHorizontal: Spacing.three,
    paddingVertical: 12,
    backgroundColor: BrandColors.surface,
  },
  pickerBtnText: { color: BrandColors.text, fontSize: 14 },
  pickerPlaceholder: { color: BrandColors.textMuted, fontSize: 14 },
  totalsBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    gap: 8,
  },
  totalsWarn: { color: BrandColors.danger, fontWeight: '700' },
  modalSearch: { marginHorizontal: Spacing.three, marginBottom: Spacing.two },
});
